name: Create Draft Release after merge
on:
  push:
    branches:
      - main
      - main-eng

jobs:
  create_draft_release:
    name: Build and create draft release
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: Tag check
        run: |
          export ORIGINAL_CODE_TAG=$(echo -n | cat version) && echo "Code tag is: $ORIGINAL_CODE_TAG"
          [[ $ORIGINAL_CODE_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+-[A-Z]{3}$ ]] || (echo $'unsuitable tag for deployment: regex \'^v[0-9]+.[0-9]+.[0-9]+-[A-Z]{3}$\' was not respected'; exit 99)
          export CODE_TAG="${ORIGINAL_CODE_TAG}"
          echo "CODE_TAG=$CODE_TAG" >> $GITHUB_ENV
          echo "PRESERVE_TAG=false" >> $GITHUB_ENV
          git fetch --unshallow origin
          git tag | grep "$CODE_TAG" && export CODE_TAG_EXISTS=true && echo "ERROR: THIS TAG ALREADY EXISTS WITHIN THE REPO! EXITING" && sed -i 's/PRESERVE_TAG=false/PRESERVE_TAG=true/g' $GITHUB_ENV  && exit 99
          echo " ==> TAGS: Checks ok!"
          echo " ==> TAGS: Tag is $CODE_TAG" && [[ $CODE_TAG_EXISTS != "true" ]] && git tag $CODE_TAG && git push --tags
          echo "ORIGINAL_CODE_TAG=$ORIGINAL_CODE_TAG" >> $GITHUB_ENV
        
      - name: Build LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          latexmk_use_xelatex: true

      - name: Create draft release
        uses: release-drafter/release-drafter@v5

      - name: Deleting tag on failure
        if: ${{ failure() }}
        run: |
          git push --delete origin $CODE_TAG