name: Create release
on:
  push:
    branches:
      - main
        
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create_release:
    name: Build and create release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        
      - name: Tag check
        run: |
          export ORIGINAL_CODE_TAG=$(echo -n | cat version) && echo "Code tag is: $ORIGINAL_CODE_TAG"
          [[ $ORIGINAL_CODE_TAG =~ ^[0-9]+.[0-9]+.[0-9]+$ ]] || (echo $'unsuitable tag for deployment: regex \'^[0-9]+.[0-9]+.[0-9]+$\' was not respected'; exit 99)
          export CODE_TAG="v${ORIGINAL_CODE_TAG}"
          echo "CODE_TAG=$CODE_TAG" >> $GITHUB_ENV
          echo "PRESERVE_TAG=true" >> $GITHUB_ENV
          git fetch --depth=10
          git tag | grep "$CODE_TAG" && export CODE_TAG_EXISTS=true && echo "ERROR: THIS TAG ALREADY EXISTS WITHIN THE REPO! EXITING" && sed -i 's/PRESERVE_TAG=false/PRESERVE_TAG=true/g' $GITHUB_ENV  && exit 99
          echo " ==> TAGS: Checks ok!"
          echo " ==> TAGS: Tag is $CODE_TAG" && [[ $CODE_TAG_EXISTS != "true" ]] && git tag $CODE_TAG && git push --tags
          echo "ORIGINAL_CODE_TAG=$ORIGINAL_CODE_TAG" >> $GITHUB_ENV
          
      - name: Build LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "*.tex"
          glob_root_file: true
          latexmk_use_xelatex: true
          post_compile: "cp cv_eng.pdf CV_Bagnoli_Alessandro_EN.pdf && cp cv_ita.pdf CV_Bagnoli_Alessandro_IT.pdf"

      - name: Create release
        run: |
          RELEASE_URL="$(gh release create ${{ env.CODE_TAG }} \
            --generate-notes \
            --title 'Curriculum Vitae ${{ env.ORIGINAL_CODE_TAG }}' \
            './CV_Bagnoli_Alessandro_EN.pdf' \
            './CV_Bagnoli_Alessandro_IT.pdf')"

          echo "RELEASE_URL=$RELEASE_URL" >> $GITHUB_ENV

      - name: Deleting tag on failure
        if: ${{ failure() }}
        run: |
          [[ "${{ env.PRESERVE_TAG }}" == "false" ]] && git push --delete origin $CODE_TAG
          
      - name: Send Telegram notification on success
        run: |
          ROCKET_EMOJI=$(echo -e '\U0001F680')
          curl --request POST \
          --url    'https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMediaGroup' \
          --header 'Accept: application/json' \
          --header 'Content-Type: multipart/form-data' \
          --header 'User-Agent: GitHub Action' \
          --form   'media=
            [
              {
                "type": "document",
                "media": "attach://CV_Bagnoli_Alessandro_EN.pdf"
              },
              {
                "type": "document",
                "media": "attach://CV_Bagnoli_Alessandro_IT.pdf",
                "caption": "'$ROCKET_EMOJI' Deploy successful! Here are your PDFs. Related release is available at ${{ env.RELEASE_URL }}"
              }
            ]
          ' \
          --form   'CV_Bagnoli_Alessandro_EN.pdf=@./CV_Bagnoli_Alessandro_EN.pdf' \
          --form   'CV_Bagnoli_Alessandro_IT.pdf=@./CV_Bagnoli_Alessandro_IT.pdf' \
          --form   'chat_id=${{ secrets.TELEGRAM_CHAT_ID }}'

      - name: Send Telegram notification on failure
        if: ${{ failure() }}
        run: |
          WARNING_EMOJI=$(echo -e '\U00026A0')
          curl --request POST \
          --url    'https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage' \
          --header 'Accept: application/json' \
          --header 'Content-Type: application/json' \
          --header 'User-Agent: GitHub Action' \
          --data '
          {
            "chat_id": "${{ secrets.TELEGRAM_CHAT_ID }}",
            "text": "'$WARNING_EMOJI' Deploy failed!"
          }
          '