name: Feature Push
on:
  push:
    branches-ignore:
      - main

jobs:
  push-to-feature:
    name: Push to feature
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        
      - name: Build LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "*.tex"
          glob_root_file: true
          latexmk_use_xelatex: true