name: Feature Push
on:
  push:
    branches-ignore:
      - main
      - main-eng
jobs:
  push-to-feature:
    name: Push to feature
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: Cache docker image
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        
      - name: Build LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          latexmk_use_xelatex: true