name: Feature Push
on:
  push:
    branches-ignore:
      - main
      - main-eng
jobs:
  push-to-feature:
    name: Push to feature
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        
      - name: Build LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "*.tex"
          glob_root_file: true
          latexmk_use_xelatex: true