name: Merge Request
on:
  pull_request:
    branches:
      - main
      - main-eng

jobs:
  build_n_test:
    name: Build and check tag
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: tag check
        run: |
          export ORIGINAL_CODE_TAG=$(echo -n | cat version) && echo "Code tag is: $ORIGINAL_CODE_TAG"
          [[ $ORIGINAL_CODE_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+-[A-Z]{3}$ ]] || (echo $'unsuitable tag for deployment: regex \'^v[0-9]+.[0-9]+.[0-9]+-[A-Z]{3}$\' was not respected'; exit 99)
          export CODE_TAG="${ORIGINAL_CODE_TAG}"
          echo "CODE_TAG=$CODE_TAG" >> $GITHUB_ENV
          echo "PRESERVE_TAG=false" >> $GITHUB_ENV
          git fetch --unshallow origin
          git tag | grep "$CODE_TAG" && export CODE_TAG_EXISTS=true && echo "ERROR: THIS TAG ALREADY EXISTS WITHIN THE REPO! EXITING" && sed -i 's/PRESERVE_TAG=false/PRESERVE_TAG=true/g' $GITHUB_ENV  && exit 99
          echo " ==> TAGS: Checks ok!"
          echo " ==> TAGS: Tag is $CODE_TAG" && [[ $CODE_TAG_EXISTS != "true" ]] && git tag $CODE_TAG && git push --tags
          echo "ORIGINAL_CODE_TAG=$ORIGINAL_CODE_TAG" >> $GITHUB_ENV
        
      - name: Build LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          latexmk_use_xelatex: true

      - name: success cleanup - deleting tag
        run: |
          [[ "${{ env.PRESERVE_TAG }}" == "false" ]] &&  git push --delete origin $CODE_TAG

      - name: deleting tag on failure
        if: ${{ failure() }}
        run: |
          [[ "${{ env.PRESERVE_TAG }}" == "false" ]] &&  git push --delete origin $CODE_TAG